AWSTemplateFormatVersion: 2010-09-09
Description: Sample Cloudformation template to create ec2 instance and transfering file from ec2 instance to s3 automatically.

Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: X.X.X.X/32  ## This is my public ip address  this will get attached to ec2-security group

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-089c26792dcb1fbd4
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: hakim-labs-key   ## i am not creating a key, i already had this and i am just attaching it 
      SecurityGroups:
        - !Ref EC2SecurityGroup   ## the above created security group gets attached here.
      BlockDeviceMappings: ## a volume is created and attached to instance of size 8 GB.
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: |
          #!/bin/bash    ## cronie has to be manually installed on aws linux instance as by default it not there. 
          sudo yum install cronie -y
          sudo systemctl start crond
          sudo systemctl enable crond

          # Setting my s3 bucket name where my s3 copy script is present and also mentioning script name and then observer the s3 cp command.
          S3_BUCKET_NAME="hakim-tutorial-labs-s3"
          SCRIPT_NAME="s3-copy-script.sh"
          LOCAL_SCRIPT_PATH="/home/ec2-user/$SCRIPT_NAME"
          LOG_FILE_PREFIX="ls_output"
          AWS_LOG_FILE="/tmp/aws_s3_cp_log.txt"

          # Copy the script from S3 to the ec2-user's home directory as the first user login is of ec2-user and ec2 -user can as well configure its cron.
          aws s3 cp s3://$S3_BUCKET_NAME/$SCRIPT_NAME $LOCAL_SCRIPT_PATH
          chmod +x $LOCAL_SCRIPT_PATH

          # Add a cron job to run the script every 2 minutes but remember cron is not set using crontab -e , but we are adding it as a script in cron.d and it will run as scheduled.
          echo "*/2 * * * * ec2-user $LOCAL_SCRIPT_PATH" > /etc/cron.d/run_script

  EC2InstanceProfile:   ## creating ec2 instance profile.
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref EC2Role

  EC2Role:   ## the actual ec2 role that gets attached to instance which will help in copying the files to/from s3.
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: EC2S3AccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                Resource: 'arn:aws:s3:::hakim-tutorial-labs-s3/*'

Outputs:
  EC2InstanceID:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
