AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 Instances, ALB, and Listener"

Resources:
  InstanceA:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-089c26792dcb1fbd4"
      InstanceType: "t2.micro"
      KeyName: "hakim-labs-key"
      SecurityGroupIds: 
        - !ImportValue "WebSecurityGroupId"
        - !ImportValue "WebSec1Id"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          service httpd enable
          service httpd start
          echo "<h1>This is instance A</h1>" > /var/www/html/index.html

  InstanceB:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-089c26792dcb1fbd4"
      InstanceType: "t2.micro"
      KeyName: "hakim-labs-key"
      SecurityGroupIds: 
        - !ImportValue "WebSecurityGroupId"
        - !ImportValue "WebSec1Id"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          service httpd enable
          service httpd start
          echo "<h1>This is instance B</h1>" > /var/www/html/index.html

  ALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Subnets:
        - subnet-b8610ac2
        - subnet-af77a4e3
        - subnet-4f556827
      SecurityGroups: 
        - !ImportValue "ALBSecurityGroupId"
      Scheme: "internet-facing"
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"

  WebTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Protocol: "HTTP"
      Port: 80
      VpcId: "vpc-19574271"
      HealthCheckProtocol: "HTTP"
      HealthCheckPort: 80
      HealthCheckPath: "/"
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Targets:
        - Id: !Ref InstanceA
        - Id: !Ref InstanceB

  ALBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: 'forward'
          TargetGroupArn: !Ref WebTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
